### ISSUE TITLE
Installation instructions do not work

### ISSUE THREAD

**Issue by ghost** [Quexington/chialisp_dev_utility#3]
Following installation instructions in README.md, I have no ```.\venv\Scripts\activate```

**Comment by Quexington** [comment]
Alright, I tested this on Windows, I was hoping it was just the same, but maybe not.  What platform are you on, maybe I can find out where the activate is.

**Comment by ghost** [comment]
Where should that venv directory come from? After a fresh clone there is only the content of your repository and there is no venv.
Is there a step missing in the instructions? Create venv?
I'm running Ubuntu 20.04 LTS.

**Comment by Quexington** [comment]
Oof, that's embarassing.  You do need to create then venv.  It should be fixed now https://github.com/Quexington/chialisp_dev_utility/commit/2b01bf515177a1e34051c2829b6604c820a209f1.  Test it out, let me know if it works.

**Comment by ghost** [comment]
Thanks!
Now I get:
```
Command 'py' not found, but can be installed with:

sudo apt install pythonpy
```
Ubuntu 20.04 LTS.

It works when I use the preinstalled python (3.8.5 fyi)
```
git clone https://github.com/Quexington/chialisp_dev_utility.git
cd chialisp_dev_utility
python3 -m venv venv
source ./venv/bin/activate
pip install -e .
```

**Comment by Quexington** [comment]
Okay, it's py on Windows, so I'll update the install instructions to include both.  It should be fixed now.
