### ISSUE TITLE
Running cdv test returns errors

### ISSUE THREAD

**Issue by trepca** [Quexington/chialisp_dev_utility#9]
Readme mentions trying examples and I tried running `cdv test` and got back 

```
../../../../.pyenv/versions/3.9.0/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
cdv/examples/tests/test_piggybank.py:6: in <module>
    from cdv.examples.drivers.piggybank_drivers import (
E   ModuleNotFoundError: No module named 'cdv.examples.drivers'
```

any ideas on how I could get it working?

**Comment by Quexington** [comment]
Yeah I am aware of this issue.  It's in main in Chia-Network/chia-dev-tools and during the next release it will be fixed but you should just have to add a __init__.py file to your test folder.

**Comment by trepca** [comment]
yep, adding init worked, thanks
